
version: '3'

services:
  schools-infra-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker 
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=schools_infra